/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WorkPackagePanel.java
 *
 * Created on Jun 10, 2009, 10:54:56 PM
 */
package net.sourceforge.fddtools.ui;

import com.nebulon.xml.fddi.Project;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import net.sourceforge.fddtools.fddi.extension.WorkPackage;
import net.sourceforge.fddtools.fddi.extension.WorkPackageObjectFactory;
import org.jdesktop.beansbinding.Binding;

/**
 *
 * @author vds
 */
public class WorkPackagePanel extends JPanel
{

    /** Creates new form WorkPackagePanel */
    private WorkPackageObjectFactory of = new WorkPackageObjectFactory();
    private Project project;

    /** Creates new form WorkPackagePanel */
    public WorkPackagePanel(Project projectIn)
    {
        //we need aspect info to properly initialize to support milestones

        project = projectIn;

        initComponents();

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter()
        {

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jScrollPaneMouseClicked(evt);
            }
        });
    }

    ActionListener addWorkPackageListener = new ActionListener()
    {
        public void actionPerformed(final ActionEvent e)
        {
            WorkPackage wp = of.createWorkPackage();
            wp.setName("<EDIT WORKPACKAGE NAME>");
            Binding binding = bindingGroup.getBinding("workPackageBinding");
            binding.unbind();
            project1.getAny().add(wp);
            binding.bind();
        }
    };

        ActionListener insertWorkPackageListener = new ActionListener()
    {
        public void actionPerformed(final ActionEvent e)
        {
            WorkPackage wp = of.createWorkPackage();
            wp.setName("<EDIT WORKPACKAGE NAME>");
            int index = workPackageTable.getSelectedRow() >= 0 ? workPackageTable.getSelectedRow() : 0;
            Binding binding = bindingGroup.getBinding("workPackageBinding");
            binding.unbind();
            project1.getAny().add(index, wp);
            binding.bind();
        }
    };

    ActionListener deleteWorkPackageListener = new ActionListener()
    {

        public void actionPerformed(final ActionEvent e)
        {
            int index = workPackageTable.getSelectedRow() >= 0 ? workPackageTable.getSelectedRow() : 0;
            Binding binding = bindingGroup.getBinding("workPackageBinding");
            binding.unbind();
            project1.getAny().remove(index);
            binding.bind();
        }
    };


    private void jScrollPaneMouseClicked(java.awt.event.MouseEvent evt)
    {
        if(SwingUtilities.isRightMouseButton(evt))
        {
            JPopupMenu addWorkPackageMenu = new JPopupMenu("Edit Menu");
            JMenuItem addItem = new JMenuItem("Add New WorkPackage");
            addWorkPackageMenu.add(addItem);
            addItem.addActionListener(addWorkPackageListener);
            addWorkPackageMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        project1 = project;
        jScrollPane1 = new javax.swing.JScrollPane();
        workPackageTable = new javax.swing.JTable();

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${workPackages}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, project1, eLProperty, workPackageTable, "workPackageBinding");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sequence}"));
        columnBinding.setColumnName("Sequence");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        workPackageTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workPackageTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workPackageTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void workPackageTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_workPackageTableMouseClicked
    {//GEN-HEADEREND:event_workPackageTableMouseClicked
        if(SwingUtilities.isRightMouseButton(evt))
        {
            JPopupMenu tableEditMenu = new JPopupMenu("Edit Menu");
            JMenuItem addItem = new JMenuItem("Add New WorkPackage (at end of list)");
            JMenuItem insertItem = new JMenuItem("Insert New WorkPackage (above this location)");
            JMenuItem deleteItem = new JMenuItem("Delete this WorkPackage");
            tableEditMenu.add(addItem);
            tableEditMenu.add(insertItem);
            tableEditMenu.add(deleteItem);
            addItem.addActionListener(addWorkPackageListener);
            insertItem.addActionListener(insertWorkPackageListener);
            deleteItem.addActionListener(deleteWorkPackageListener);
            tableEditMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_workPackageTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.nebulon.xml.fddi.Project project1;
    private javax.swing.JTable workPackageTable;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
