//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.11 at 08:52:34 PM CST 
//
package com.nebulon.xml.fddi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nebulon.xml._2004.fddi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

    private final static QName _NoteInitials_QNAME = new QName("", "initials");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nebulon.xml._2004.fddi
     * 
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link AspectInfo }
     * 
     */
    public AspectInfo createAspectInfo()
    {
        return new AspectInfo();
    }

    /**
     * Create an instance of {@link Progress.Kpi }
     * 
     */
    public Progress.Kpi createProgressKpi()
    {
        return new Progress.Kpi();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature()
    {
        return new Feature();
    }

    /**
     * Create an instance of {@link Milestone }
     * 
     */
    public Milestone createMilestone()
    {
        return new Milestone();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram()
    {
        return new Program();
    }

    /**
     * Create an instance of {@link MilestoneInfo }
     * 
     */
    public MilestoneInfo createMilestoneInfo()
    {
        return new MilestoneInfo();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity()
    {
        return new Activity();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject()
    {
        return new Project();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote()
    {
        return new Note();
    }

    /**
     * Create an instance of {@link Aspect }
     * 
     */
    public Aspect createAspect()
    {
        return new Aspect();
    }

    /**
     * Create an instance of {@link Progress }
     * 
     */
    public Progress createProgress()
    {
        return new Progress();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject()
    {
        return new Subject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "initials", scope = Note.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNoteInitials(String value)
    {
        return new JAXBElement<String>(_NoteInitials_QNAME, String.class, Note.class, value);
    }
}
